//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 02:10:08 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.csapi.org/schema/parlayx/sms/receive/v2_0/local")
package com.nortal.telecom.smsgateway.model.receivesms;
