//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 09:55:08 AM EEST 
//


package com.nortal.telecom.smsgateway.model.sendsms;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="deliveryStatus" type="{http://www.csapi.org/schema/parlayx/sms/v2_0}DeliveryStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryInformation", namespace = "http://www.csapi.org/schema/parlayx/sms/v2_0", propOrder = {
    "address",
    "deliveryStatus"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2013-08-28T09:55:08+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
public class DeliveryInformation {

    @XmlElement(namespace = "", required = true)
    @XmlSchemaType(name = "anyURI")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-08-28T09:55:08+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected String address;
    @XmlElement(namespace = "", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-08-28T09:55:08+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    protected DeliveryStatus deliveryStatus;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-08-28T09:55:08+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-08-28T09:55:08+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the deliveryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryStatus }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-08-28T09:55:08+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public DeliveryStatus getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * Sets the value of the deliveryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryStatus }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2013-08-28T09:55:08+03:00", comments = "JAXB RI vhudson-jaxb-ri-2.1-2")
    public void setDeliveryStatus(DeliveryStatus value) {
        this.deliveryStatus = value;
    }

}
