//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.29 at 10:38:57 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_0/local", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nortal.telecom.smsgateway.model.sendsms;
